# -*- coding: utf-8 -*-
"""
/***************************************************************************
 waterwell_interaction
                                 A QGIS plugin
 Simulação de interferência de poços e rios com interface gráfica avançada
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-25
        copyright            : (C) 2024 by Diogo Caribé de Sousa
        email                : diogo.sousa@inema.ba.gov.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load waterwell_interaction class from file waterwell_interaction.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .waterwell_interaction import waterwell_interaction
    return waterwell_interaction(iface)
